### PR TITLE
fix(cef): unbreak agentmux-cef compile on macOS with public cef-rs 146

### LINKED ISSUE #1130: bug(macOS): agentmux-cef fails to compile on macOS at HEAD — public cef-rs 146.7.0 missing AgentMux libcef patch + on_pre_key_event signature drift
## Summary

A fresh clone of `agentmuxai/agentmux` at `main` (HEAD `2abe5968`) cannot compile the `agentmux-cef` host on macOS (Apple Silicon, Darwin 25.2). Two distinct errors block the build. Both are real defects in `main`, not local env drift.

## Environment

- macOS 25.2 (Darwin), Apple Silicon (`aarch64-apple-darwin`)
- Rust toolchain (system default)
- Fresh `git clone` → fresh `~/.cargo/registry` resolution
- `Cargo.lock` (unmodified from origin/main) pins `cef = 146.7.0+146.0.12` and `cef-dll-sys = 146.7.0+146.0.12` from crates.io
- `Cargo.toml` declares `cef = { version = \"146\", default-features = false, features = [\"build-util\"] }` — **no `[patch.crates-io]` override**

## Reproduction

\`\`\`bash
git clone git@github.com:agentmuxai/agentmux.git
cd agentmux
task dev          # or: cargo build --release -p agentmux-cef
\`\`\`

### 1. \`on_pre_key_event\` trait signature drift on macOS

\`\`\`
error[E0053]: method \`on_pre_key_event\` has an incompatible type for trait
   --> agentmux-cef/src/client/handlers.rs:163:24
    |
163 |             _os_event: Option<&mut crate::OsKeyEvent>,
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected \`*mut u8\`, found \`std::option::Option<&mut c_void>\`
    |
    = note: expected signature \`fn(&AgentMuxKeyboardHandler, Option<&mut cef::Browser>, Option<&cef::KeyEvent>, *mut u8, Option<&mut _>) -> _\`
               found signature \`fn(&AgentMuxKeyboardHandler, Option<&mut cef::Browser>, Option<&cef::KeyEvent>, Option<&mut c_void>, Option<&mut _>) -> _\`
\`\`\`

**Root cause.** The \`OsKeyEvent\` type alias in \`agentmux-cef/src/main.rs:55-63\` resolves to:
- Windows → \`cef::sys::MSG\`
- Linux → \`cef::sys::_XEvent\`
- macOS → \`std::ffi::c_void\`

The trait signature shape \`Option<&mut OsKeyEvent>\` happens to match Windows' \`ImplKeyboardHandler\` (\`Option<&mut MSG>\`), but cef-rs 146.7.0's macOS binding declares the parameter as a raw \`*mut u8\` — not an \`Option<&mut T>\`. So the trait impl is unsatisfiable on Darwin regardless of what \`OsKeyEvent\` aliases to.

Verified against the locked source:
- \`~/.cargo/registry/src/.../cef-146.7.0+146.0.12/src/bindings/aarch64_apple_darwin.rs:20458\` → \`os_event: *mut u8\`
- \`~/.cargo/registry/src/.../cef-146.7.0+146.0.12/src/bindings/x86_64_pc_windows_msvc.rs:20472\` → \`os_event: Option<&mut MSG>\`

### 2. Missing \`begin_window_drag\` field on \`_cef_window_t\`

\`\`\`
error[E0609]: no field \`begin_window_drag\` on type \`_cef_window_t\`
   --> agentmux-cef/src/ui_tasks.rs:199:49
\`\`\`

**Root cause.** \`ui_tasks.rs\` documents (lines 162, 176-184) that this field is an AgentMux extension appended to \`_cef_window_t\` by a custom-patched \`cef-dll-sys\`, paired with the patched \`libcef.so\` from the [\`a5af/cef\` fork, branch \`agentmux/7680-drag-rightclick-and-transparency\`](https://github.com/a5af/cef) (per \`docs/cef-build/build-patched-libcef.md\`).

The workspace \`Cargo.toml\` does not declare a \`[patch.crates-io]\` override mapping \`cef-dll-sys\` to the patched fork, so cargo resolves to public crates.io \`cef-dll-sys 146.7.0+146.0.12\`, whose \`_cef_window_t\` definition (verified at \`~/.cargo/registry/src/.../cef-dll-sys-146.7.0+146.0.12/src/bindings/aarch64_apple_darwin.rs\`) does not contain \`begin_window_drag\`.

The code block is gated \`#[cfg(not(target_os = \"windows\"))]\`, so it tries to compile on macOS even though the patched libcef is described in the docs as a Linux drag fix.

## Why CI didn't catch this

The repo's only GitHub Actions workflow is \`release-consistency.yml\`, which only checks version-file consistency on PRs touching \`VERSION_HISTORY.md\`. **No CI builds the Rust host on any platform**, so any code that compiles only against a privately-patched cef-rs will silently land on \`main\` and break fresh clones.

## Suggested remediation (non-exhaustive)

1. **Add a \`build\` CI workflow** that runs \`cargo check -p agentmux-cef --target {aarch64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu}\` on every PR. This is the load-bearing fix — without it, regressions like this will keep happening.
2. For (1) \`on_pre_key_event\`: change \`agentmux-cef/src/client/handlers.rs:163\` so the macOS impl uses \`*mut u8\` (per the compiler's suggested fix), or restructure \`OsKeyEvent\` so the trait shape per platform matches cef-rs's bindings.
3. For (2) \`begin_window_drag\`: either add a \`[patch.crates-io]\` block pointing \`cef-dll-sys\` at the AgentMux fork (and document the requirement in \`BUILD.md\`), gate the call site behind a cargo feature that's off by default (\`patched-libcef\`), or stub the FFI extension lookup so unpatched builds fall back to no-op drag rather than failing to compile.

## Notes

- \`task package:macos\` is currently a \`[TODO]\` stub (\`echo \"macOS packaging not yet implemented.\"\`), so the only way to launch on macOS today is \`task dev\` — which is exactly what this issue blocks.
- The agentmux-srv backend builds and runs fine on macOS; only the agentmux-cef host is broken.

### PR DESCRIPTION
**Pull request by a5af**
## Summary

- Splits `wrap_keyboard_handler!` into three `#[cfg(target_os = ...)]` blocks so the `on_pre_key_event` trait impl matches cef-rs's per-platform `os_event` signature (`Option<&mut MSG>` / `Option<&mut XEvent>` / `*mut u8`). Removes the now-unused `OsKeyEvent` type alias.
- Gates the `_cef_window_t::begin_window_drag` FFI call site behind a new `patched-libcef` cargo feature (default off) so unpatched checkouts (= default crates.io `cef-dll-sys`) compile. Patched builds (`--features patched-libcef`) behave identically to before.

Closes #1130.

## Why this matters

A fresh clone at `main` HEAD fails `cargo build -p agentmux-cef` on macOS:

```
error[E0053]: method `on_pre_key_event` has an incompatible type for trait
   --> agentmux-cef/src/client/handlers.rs:163:24

error[E0609]: no field `begin_window_drag` on type `_cef_window_t`
   --> agentmux-cef/src/ui_tasks.rs:199:49
```

Both are real defects in `main`. The only CI workflow today is `release-consistency.yml`, which doesn't compile the Rust host on any platform — so this drift went unnoticed. Filing a follow-up issue for adding a `cargo check` matrix CI job would close the gap that allowed this in.

## Behavior

| Build | macOS | Linux | Windows |
|-------|-------|-------|---------|
| Default (`task dev`, `cargo build`) | Compiles + runs. Native left-click window drag is a no-op (warns once per attempt). | Same as macOS. | Unchanged — drag is Windows-native via WM_NCLBUTTONDOWN, doesn't go through `begin_window_drag`. |
| `--features patched-libcef` (with patched `cef-dll-sys` via `[patch.crates-io]`) | Identical to prior behavior. | Identical to prior behavior. | Unchanged. |

The runtime ABI-mismatch guard in `StartWindowDragTask` (size-check against `cef_base_ref_counted_t.size`) is preserved, so a `--features patched-libcef` binary running against an unpatched `libcef.dylib` still no-ops cleanly with a warn.

## Test plan

- [x] `cargo check -p agentmux-cef --release` — clean (warnings only).
- [x] `cargo build --release -p agentmux-cef` — finishes in 43.6s on Apple Silicon.
- [x] `task dev` advances past the compile stage and starts the host (then panics at `cef-rs library_loader.rs:20` because `libcef.dylib` isn't bundled — separate runtime/setup issue, not in scope).
- [ ] Windows: confirm `cargo build -p agentmux-cef` still passes (unchanged code paths, but verifying CI).
- [ ] `cargo build --features patched-libcef` against a patched `cef-dll-sys` to confirm the gated path still compiles.

## Notes for reviewers

- Default branch on a clean clone now compiles on macOS but the host still won't launch without bundling a `libcef.dylib`. That's a separate dev-setup issue worth filing.
- `OsKeyEvent` is removed from `agentmux-cef/src/main.rs` — verified it had no other consumers (grep returned only the now-rewritten `handlers.rs:163` site).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by a5af** [comment]
@codex review

File: agentmux-cef/Cargo.toml [hunk 1]
```diff
@@ -16,6 +16,13 @@ default = []
 sandbox = ["cef/sandbox"]
 # Opt-in for dev_authfile unit tests that touch the filesystem and Win32 ACL APIs
 test-authfile = []
+# Enables call sites that depend on the AgentMux libcef fork
+# (https://github.com/a5af/cef, branch agentmux/7680-drag-rightclick-and-transparency).
+# Specifically: `_cef_window_t::begin_window_drag` (used by StartWindowDragTask).
+# Requires a matching patched cef-dll-sys via [patch.crates-io] in the workspace
+# Cargo.toml. Default OFF so unpatched checkouts compile — native left-click
+# window drag is a no-op without the patch.
+patched-libcef = []
```
[the remark this answers is not in the document]
Comment (a5af) [reply agentmux-cef/Cargo.toml:25]: Thanks — but this rests on a premise that doesn't hold: **Linux production builds weren't compiling either before this PR.** Verified facts on `main` at `2abe5968` (the base of this PR):

1. `Cargo.lock` pins `cef-dll-sys 146.7.0+146.0.12` from `registry+https://github.com/rust-lang/crates.io-index` — i.e., the unpatched public crate, not a fork.
2. `~/.cargo/registry/src/.../cef-dll-sys-146.7.0+146.0.12/src/bindings/x86_64_unknown_linux_gnu.rs` contains zero matches for `begin_window_drag` — same as the macOS binding.
3. Workspace has no `[patch.crates-io]` block, no `.cargo/config.toml` source replacement, no git-source override.
4. The only CI workflow is `release-consistency.yml`. Nothing builds the Rust host on any platform.

So `cargo build -p agentmux-cef` was failing on Linux with the identical `E0609: no field begin_window_drag` error before this PR — just silently, because no CI surfaced it. PR #663's commit message ([ce2a806e](https://github.com/agentmuxai/agentmux/commit/ce2a806e)) explicitly notes a `cef-dll-sys binding patch (begin_window_drag fn pointer at end of _cef_window_t, size assert 888→896)`, but that patched fork is no longer pinned in `Cargo.lock`. The patch got de-wired somewhere between #663 and HEAD.

What this PR changes for Linux:
- **Before:** Linux compile fails at HEAD. No production build exists. Drag = N/A.
- **After:** Linux compiles. Native drag is a no-op (warns once per attempt) unless built with `--features patched-libcef` + a `[patch.crates-io]` mapping `cef-dll-sys` back to a fork that carries the binding patch.

In other words: this PR strictly improves the Linux state. To **restore** native drag in the AppImage, two things are needed (out of scope for this compile fix):

1. Re-publish the patched `cef-dll-sys` (e.g., from `a5af/cef` or an equivalent fork) and add `[patch.crates-io] cef-dll-sys = { git = "...", branch = "..." }` to the workspace `Cargo.toml`.
2. Add `--features patched-libcef` to `Taskfile.yml::build:host:linux`.

I'll add this to the PR description so reviewers see the full Linux-recovery path. I'd rather not do (2) alone in this PR — it would re-break Linux compile immediately because (1) isn't in place. Happy to do both in a follow-up if maintainers can point me at the patched `cef-dll-sys` fork's current home.
