### PR TITLE
fix(cef): pin Cargo to CEF 146 until 7778 drag/right-click/transparency patches are forward-ported

### PR DESCRIPTION
**Pull request by AgentU-asaf**
## Summary

PR #1221 (CEF 146 → 148 source bump) inadvertently broke `build:host:linux` because the agentmux patches that add `_cef_window_t::begin_window_drag` (the source code addition behind `StartWindowDragTask` for native Wayland/X11 window drag) **only exist on the `agentmuxai/cef@agentmux/7680-drag-rightclick-and-transparency` branch** — they have not been forward-ported to the `agentmux/7778-…` branch yet.

## What happened

- `cargo build --release -p agentmux-cef --features patched-libcef` fails at `ui_tasks.rs:215` with `error[E0609]: no field begin_window_drag on type _cef_window_t` (the cef-dll-sys 148 binding lacks the field).
- The Linux Taskfile path has been silently building **without** `--features patched-libcef` since the bump, which compiles the `#[cfg(not(feature = "patched-libcef"))]` no-op branch. Every `start_window_drag` IPC since then warns "patched-libcef feature disabled — native drag is a no-op."
- **Title-bar drag has silently been broken on every Linux AppImage built since #1221 was merged**, regardless of ozone platform.

## What this PR does

Pins `cef = "146"` in `agentmux-cef/Cargo.toml` + refreshes `Cargo.lock` accordingly. With this pin, the patched cef-dll-sys 146 binding (which has `begin_window_drag`) is used, `--features patched-libcef` compiles, and the existing patched `libcef.so` (built from `agentmuxai/cef@agentmux/7680-drag-rightclick-and-transparency` via `scripts/resolve-cef-runtime.sh`) is the matching runtime.

**Explicitly temporary.** The proper fix is two follow-up PRs:

1. New branch `agentmuxai/cef@agentmux/7778-drag-rightclick-and-transparency` cherry-picking these commits onto upstream `7778`:
   - `af485ed2` `views: Add CefWindow::BeginWindowDrag()`
   - `010f616f` `views: PR review on BeginWindowDrag` (the X11 fix using `display::Screen::Get()->GetCursorScreenPoint()` — without this `_NET_WM_MOVERESIZE` ignores the drag request because `gfx::Point()` gives an invalid anchor)
   - `130af663` `views: Annotate CefWindow::BeginWindowDrag with added=14600`
   - `41802fe6` `Patch A: Let right-clicks on HTCAPTION fall through to renderer`
   - `b921ffe1` `Support transparent window in Views framework`
   - The five `views: …transparency cascade…` follow-ups
2. `cef-dll-sys` 148 binding adds the `begin_window_drag` field at the end of `_cef_window_t`.

Once both land and a CEF 148 `libcef.so` is rebuilt and bundled (the multi-hour `~/cef-build` step), Cargo can move back to `"148"`.

## Platforms

- **macOS, Windows: unaffected.** macOS already builds CEF 148 from `agentmuxai/cef@agentmux/7778-process-requirement` (which has only the macOS-26 patch, no drag patch); Windows doesn't use `--features patched-libcef` (native drag goes through `SetWindowsHookEx` + `WM_NCHITTEST`).
- **Linux: restored.** `task build:host` produces a host binary that calls the native `BeginWindowDrag` slot in libcef.so; title-bar drag works on both Wayland and X11 ozone modes.

## Test plan

- [x] `cargo build --release -p agentmux-cef --features patched-libcef` succeeds (verified locally on this branch)
- [x] Resulting host binary `strings` shows `BeginWindowDrag returned` info string (the patched path) — **not** `patched-libcef feature disabled` (the no-op path)
- [x] Title-bar drag works on Wayland default
- [x] Title-bar drag works with `--ozone-platform=x11` (validates the `010f616f` X11 cursor-screen-point fix)
- [ ] CI build:host:linux green
- [ ] macOS and Windows tasks build clean (no Cargo resolver fights)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by a5af** [comment]
@codex review
