### PR TITLE
fix(container): pass global_output_zone through container-exec path (unbreak main)

### PR DESCRIPTION
**Pull request by AgentA-asaf**
## Problem

`main` (`3e866dc0`) does not compile:

```
error[E0061]: this function takes 6 arguments but 5 arguments were supplied
  --> agentmux-srv/src/backend/blockcontroller/subprocess.rs:1309:13
  argument #6 of type `Option<&str>` is missing
note: function defined here
  --> agentmux-srv/src/backend/blockcontroller/shell.rs:1220:8
```

## Root cause — semantic merge conflict (both PRs green individually)

- **#1399** (globalize agent transcript) added a 6th param `global_output_zone: Option<&str>` to `handle_append_block_file` and updated the **subprocess / persistent / acp** stdout readers to resolve the zone once and pass it.
- **#1357** (container Phase 2) merged in parallel and added a *new* call site — `SubprocessController::publish_line`, the container-exec output reader — built against the **old 5-arg** signature.

Neither PR's CI compiled the *merged* tree, so the break only surfaces on `main`.

## Fix

Resolve the agent's global transcript zone **once** before the container-exec reader loop (via the existing `resolve_global_output_zone`), thread it through `publish_line`, and pass it to `handle_append_block_file`. This is byte-for-byte the same pattern the other three controllers already use — in particular it does **not** add a per-line store lookup on the hot output path.

## Verification

- `task build:backend` → `Finished release profile [optimized] in 4m 06s` (only pre-existing warnings; the E0061 error is gone).

This is the same fix already carried on the `agenta/release-v0.45.0` branch; landing it standalone unblocks `main` for everyone independent of the release.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by a5af** [comment]
@codex review
