### ISSUE TITLE
bug(macOS): agentmux-cef fails to compile on macOS at HEAD — public cef-rs 146.7.0 missing AgentMux libcef patch + on_pre_key_event signature drift

### ISSUE THREAD

**Issue by a5af** [agentmuxai/agentmux#1130]
## Summary

A fresh clone of `agentmuxai/agentmux` at `main` (HEAD `2abe5968`) cannot compile the `agentmux-cef` host on macOS (Apple Silicon, Darwin 25.2). Two distinct errors block the build. Both are real defects in `main`, not local env drift.

## Environment

- macOS 25.2 (Darwin), Apple Silicon (`aarch64-apple-darwin`)
- Rust toolchain (system default)
- Fresh `git clone` → fresh `~/.cargo/registry` resolution
- `Cargo.lock` (unmodified from origin/main) pins `cef = 146.7.0+146.0.12` and `cef-dll-sys = 146.7.0+146.0.12` from crates.io
- `Cargo.toml` declares `cef = { version = \"146\", default-features = false, features = [\"build-util\"] }` — **no `[patch.crates-io]` override**

## Reproduction

\`\`\`bash
git clone git@github.com:agentmuxai/agentmux.git
cd agentmux
task dev          # or: cargo build --release -p agentmux-cef
\`\`\`

### 1. \`on_pre_key_event\` trait signature drift on macOS

\`\`\`
error[E0053]: method \`on_pre_key_event\` has an incompatible type for trait
   --> agentmux-cef/src/client/handlers.rs:163:24
    |
163 |             _os_event: Option<&mut crate::OsKeyEvent>,
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected \`*mut u8\`, found \`std::option::Option<&mut c_void>\`
    |
    = note: expected signature \`fn(&AgentMuxKeyboardHandler, Option<&mut cef::Browser>, Option<&cef::KeyEvent>, *mut u8, Option<&mut _>) -> _\`
               found signature \`fn(&AgentMuxKeyboardHandler, Option<&mut cef::Browser>, Option<&cef::KeyEvent>, Option<&mut c_void>, Option<&mut _>) -> _\`
\`\`\`

**Root cause.** The \`OsKeyEvent\` type alias in \`agentmux-cef/src/main.rs:55-63\` resolves to:
- Windows → \`cef::sys::MSG\`
- Linux → \`cef::sys::_XEvent\`
- macOS → \`std::ffi::c_void\`

The trait signature shape \`Option<&mut OsKeyEvent>\` happens to match Windows' \`ImplKeyboardHandler\` (\`Option<&mut MSG>\`), but cef-rs 146.7.0's macOS binding declares the parameter as a raw \`*mut u8\` — not an \`Option<&mut T>\`. So the trait impl is unsatisfiable on Darwin regardless of what \`OsKeyEvent\` aliases to.

Verified against the locked source:
- \`~/.cargo/registry/src/.../cef-146.7.0+146.0.12/src/bindings/aarch64_apple_darwin.rs:20458\` → \`os_event: *mut u8\`
- \`~/.cargo/registry/src/.../cef-146.7.0+146.0.12/src/bindings/x86_64_pc_windows_msvc.rs:20472\` → \`os_event: Option<&mut MSG>\`

### 2. Missing \`begin_window_drag\` field on \`_cef_window_t\`

\`\`\`
error[E0609]: no field \`begin_window_drag\` on type \`_cef_window_t\`
   --> agentmux-cef/src/ui_tasks.rs:199:49
\`\`\`

**Root cause.** \`ui_tasks.rs\` documents (lines 162, 176-184) that this field is an AgentMux extension appended to \`_cef_window_t\` by a custom-patched \`cef-dll-sys\`, paired with the patched \`libcef.so\` from the [\`a5af/cef\` fork, branch \`agentmux/7680-drag-rightclick-and-transparency\`](https://github.com/a5af/cef) (per \`docs/cef-build/build-patched-libcef.md\`).

The workspace \`Cargo.toml\` does not declare a \`[patch.crates-io]\` override mapping \`cef-dll-sys\` to the patched fork, so cargo resolves to public crates.io \`cef-dll-sys 146.7.0+146.0.12\`, whose \`_cef_window_t\` definition (verified at \`~/.cargo/registry/src/.../cef-dll-sys-146.7.0+146.0.12/src/bindings/aarch64_apple_darwin.rs\`) does not contain \`begin_window_drag\`.

The code block is gated \`#[cfg(not(target_os = \"windows\"))]\`, so it tries to compile on macOS even though the patched libcef is described in the docs as a Linux drag fix.

## Why CI didn't catch this

The repo's only GitHub Actions workflow is \`release-consistency.yml\`, which only checks version-file consistency on PRs touching \`VERSION_HISTORY.md\`. **No CI builds the Rust host on any platform**, so any code that compiles only against a privately-patched cef-rs will silently land on \`main\` and break fresh clones.

## Suggested remediation (non-exhaustive)

1. **Add a \`build\` CI workflow** that runs \`cargo check -p agentmux-cef --target {aarch64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu}\` on every PR. This is the load-bearing fix — without it, regressions like this will keep happening.
2. For (1) \`on_pre_key_event\`: change \`agentmux-cef/src/client/handlers.rs:163\` so the macOS impl uses \`*mut u8\` (per the compiler's suggested fix), or restructure \`OsKeyEvent\` so the trait shape per platform matches cef-rs's bindings.
3. For (2) \`begin_window_drag\`: either add a \`[patch.crates-io]\` block pointing \`cef-dll-sys\` at the AgentMux fork (and document the requirement in \`BUILD.md\`), gate the call site behind a cargo feature that's off by default (\`patched-libcef\`), or stub the FFI extension lookup so unpatched builds fall back to no-op drag rather than failing to compile.

## Notes

- \`task package:macos\` is currently a \`[TODO]\` stub (\`echo \"macOS packaging not yet implemented.\"\`), so the only way to launch on macOS today is \`task dev\` — which is exactly what this issue blocks.
- The agentmux-srv backend builds and runs fine on macOS; only the agentmux-cef host is broken.
