### PR TITLE
fix(identity): restore resolve_provider_alias, broken by #2267's dead-code sweep

### PR DESCRIPTION
**Pull request by Agent2-asaf**
## Summary
`main` is currently broken for `cargo check --workspace --tests` (confirmed via CI on an unrelated PR — both `windows-latest` and `ubuntu-latest` fail with `error[E0425]: cannot find function resolve_provider_alias`).

Root cause: #2267 ("delete confirmed-dead Rust + frontend code") deleted `resolve_provider_alias` from `backend/providers.rs`, believing it had zero callers per its audit re-verification pass. But #2263 (merged immediately before it) had just added a real caller in `identity/resolver.rs:324`'s `provider_class()` — a P1 fix ensuring `provider_class` and `get_provider` can't disagree on an alias ID. The "zero-caller" re-check missed this call site.

Fix: restored the function verbatim from #2267's own diff. Nothing else changed — the same commit's unrelated deletion of `resolver.rs`'s genuinely-unused `oauth_status::UNKNOWN` const is correct and left alone.

## Test plan
- [x] `cargo check -p agentmux-srv --tests` — now succeeds (was failing before this fix, reproduced locally).
- [x] `cargo test -p agentmux-srv --bin agentmux-srv identity::resolver` — 30 passed, 0 failed, including `provider_class_resolves_aliases_to_the_same_result_as_canonical`.

## Priority
This blocks CI for every open PR in the repo, not just this fix. Requesting a fast merge.

### CODE REVIEW

**Comment by a5af** [comment]
@codex review
